### ISSUE TITLE
Error updating via Web UI

### ISSUE THREAD

**Issue by ravensorb** [lidarr/Lidarr#557]
**Describe the bug**
Update via UI failed

**To Reproduce**
1. Web Interface
2. Install Update

**Expected behavior**
Update installs correctly

**Logs**
```
18-12-2 06:23:28.2|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

[v0.4.0.524] System.ComponentModel.Win32Exception (0x80004005): ApplicationName='mono', CommandLine='--debug /tmp/lidarr_update/Lidarr.Update.exe 19757 /tmp/lidarr_update /Lidarr/Lidarr.exe /data=/usr/share/Lidarr /nobrowser', CurrentDirectory='', Native error= Cannot find the specified file
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x002dc] in <b3922b7d60404fa9ae645f1fb97f5b6b>:0 
  at System.Diagnostics.Process.Start () [0x0003a] in <b3922b7d60404fa9ae645f1fb97f5b6b>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at NzbDrone.Common.Processes.ProcessProvider.Start (System.String path, System.String args, System.Collections.Specialized.StringDictionary environmentVariables, System.Action`1[T] onOutputDataReceived, System.Action`1[T] onErrorDataReceived) [0x00194] in <f4075cfd02314b40ae0026e1c54c8c6f>:0 
  at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate (NzbDrone.Core.Update.UpdatePackage updatePackage) [0x00242] in <c476143053e2426eaa6b568f53705d08>:0 
  at NzbDrone.Core.Update.InstallUpdateService.Execute (NzbDrone.Core.Update.Commands.ApplicationUpdateCommand message) [0x0006e] in <c476143053e2426eaa6b568f53705d08>:0 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000f6] in <c476143053e2426eaa6b568f53705d08>:0 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2) [0x00035] in <07a075f1d23046ea85ee23d71b0a0a37>:0 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x0008c] in <c476143053e2426eaa6b568f53705d08>:0 
```

**System info (please complete the following information):**
 - FreeNas 11.2-STABLE Jail
 - Lidarr Version: 0.4.0.524
 - Mono Version: 5.10.1.57
 - DB Migration: 20
 - AppData directory: /usr/share/Lidarr
 - Startup directory: /Lidarr
 - Mode: Console

**Comment by Qstick** [comment]
Is this fixed with 0.5.0.583?

**Comment by ravensorb** [comment]
Not sure -- I did a manual update (downloaded the latest and installed over the current version).  I try the auto update again with the next version.

**Comment by Qstick** [comment]
OK, closing for now, if you notice it again we can re-open

**Comment by ravensorb** [comment]
Looks like this issue is still occurring and I am not sure where to look to trouble shoot,

19-2-15 05:53:40.1|Info|InstallUpdateService|Preparing client
19-2-15 05:53:40.2|Info|InstallUpdateService|Starting update client /tmp/lidarr_update/Lidarr.Update.exe
19-2-15 05:53:40.2|Info|InstallUpdateService|Lidarr will restart shortly.
19-2-15 05:53:40.2|Info|InstallUpdateService|Updater Arguments: 9398 /tmp/lidarr_update /Lidarr/Lidarr.exe /data=/usr/share/Lidarr /nobrowser
19-2-15 05:53:40.3|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

[v0.5.0.576] System.ComponentModel.Win32Exception (0x80004005): ApplicationName='mono', CommandLine='--debug /tmp/lidarr_update/Lidarr.Update.exe 9398 /tmp/lidarr_update /Lidarr/Lidarr.exe /data=/usr/share/Lidarr /nobrowser', CurrentDirectory='', Native error= Cannot find the specified file
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x002dc] in <b3922b7d60404fa9ae645f1fb97f5b6b>:0 
  at System.Diagnostics.Process.Start () [0x0003a] in <b3922b7d60404fa9ae645f1fb97f5b6b>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at NzbDrone.Common.Processes.ProcessProvider.Start (System.String path, System.String args, System.Collections.Specialized.StringDictionary environmentVariables, System.Action`1[T] onOutputDataReceived, System.Action`1[T] onErrorDataReceived) [0x00194] in <334091f3d4fd471b87259e9b76137132>:0 
  at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate (NzbDrone.Core.Update.UpdatePackage updatePackage) [0x00242] in <11b2a49b22bf4cfebffe8bb8c41e23b6>:0 
  at NzbDrone.Core.Update.InstallUpdateService.Execute (NzbDrone.Core.Update.Commands.ApplicationUpdateCommand message) [0x0006e] in <11b2a49b22bf4cfebffe8bb8c41e23b6>:0 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000f6] in <11b2a49b22bf4cfebffe8bb8c41e23b6>:0 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2) [0x00035] in <07a075f1d23046ea85ee23d71b0a0a37>:0 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messag

**Comment by jkoopmann** [comment]
Same here
